# SPDX-License-Identifier: Apache-2.0
---
# SAP Note: 3024346 - Linux Kernel Settings for NetApp NFS
#
- name: Configure - Display SAP note number 3024346 and its version
  ansible.builtin.debug:
    msg: "SAP note {{ (__sap_hana_preconfigure_sapnotes_versions | selectattr('number', 'match', '^3024346$') | first).number }}
          (version {{ (__sap_hana_preconfigure_sapnotes_versions | selectattr('number', 'match', '^3024346$') | first).version }}): Linux kernel settings for NetApp NFS"

- name: Set kernel tunables for NetApp NFS as per SAP note 3024346
  when:
    - sap_hana_preconfigure_use_netapp_settings_nfs|d(false)
    - sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_3024346|d(false)
  block:

    - name: Ensure correct entries in file '{{ __sap_hana_preconfigure_etc_sysctl_netapp_hana_conf }}'
      ansible.builtin.lineinfile:
        path: "{{ __sap_hana_preconfigure_etc_sysctl_netapp_hana_conf }}"
        create: yes
        mode: 0644
        regexp: ^{{ line_item.name }}.*
        line: "{{ line_item.name }}={{ line_item.value }}"
        state: present
      with_items: "{{ __sap_hana_preconfigure_kernel_parameters_netapp_nfs }}"
      loop_control:
        loop_var: line_item

    - name: Construct the command for getting all current parameters of file '{{ __sap_hana_preconfigure_etc_sysctl_netapp_hana_conf }}'
      ansible.builtin.command: awk 'BEGIN{FS="="; printf ("sysctl ")}{printf ("%s ", $1)}' "{{ __sap_hana_preconfigure_etc_sysctl_netapp_hana_conf }}"
      register: __sap_hana_preconfigure_register_netapp_sysctl_command
      changed_when: false

    - name: Get all currently active values of the parameters of file '{{ __sap_hana_preconfigure_etc_sysctl_netapp_hana_conf }}'
      ansible.builtin.shell: "{{ __sap_hana_preconfigure_register_netapp_sysctl_command.stdout }} | sed 's,\t, ,g'"
      register: __sap_hana_preconfigure_register_netapp_sysctl_p_output_old
      changed_when: false

    - name: Reload kernel parameters from file '{{ __sap_hana_preconfigure_etc_sysctl_netapp_hana_conf }}'
      ansible.builtin.command: sysctl -p "{{ __sap_hana_preconfigure_etc_sysctl_netapp_hana_conf }}"
      register: __sap_hana_preconfigure_register_netapp_sysctl_p_output_new
      changed_when: __sap_hana_preconfigure_register_netapp_sysctl_p_output_old.stdout != __sap_hana_preconfigure_register_netapp_sysctl_p_output_new.stdout

    - name: Display kernel parameters for NetApp NFS, old
      ansible.builtin.debug:
        var: __sap_hana_preconfigure_register_netapp_sysctl_p_output_old.stdout_lines

    - name: Display kernel parameters for NetApp NFS
      ansible.builtin.debug:
        var: __sap_hana_preconfigure_register_netapp_sysctl_p_output_new.stdout_lines

    - name: Set kernel tunable for NFSv3 as per SAP note 3024346
      ansible.builtin.lineinfile:
        path: /etc/modprobe.d/sunrpc.conf
        create: yes
        mode: 0644
        regexp: '^options sunrpc tcp_max_slot_table_entries'
        line: options sunrpc tcp_max_slot_table_entries=128
      when: sap_hana_preconfigure_use_netapp_settings_nfsv3
