# SPDX-License-Identifier: Apache-2.0
---

# vars file for sap_general_preconfigure

__sap_general_preconfigure_packages_x86_64:
  - uuidd
  - libnsl
  - tcsh
  - psmisc
  - nfs-utils
  - bind-utils
  - compat-sap-c++-9
  - compat-sap-c++-10
  - compat-sap-c++-11
# English locale packages are required as per SAP note 2369910:
  - langpacks-en
  - glibc-langpack-en

__sap_general_preconfigure_packages_ppc64le:
  - uuidd
  - libnsl
  - tcsh
  - psmisc
  - nfs-utils
  - bind-utils
  - compat-sap-c++-9
  - compat-sap-c++-10
  - compat-sap-c++-11
# English locale packages are required as per SAP note 2369910:
  - langpacks-en
  - glibc-langpack-en

__sap_general_preconfigure_packages_s390x:
  - uuidd
  - libnsl
  - tcsh
  - psmisc
  - nfs-utils
  - bind-utils
  - compat-sap-c++-10
# English locale packages are required as per SAP note 2369910:
  - langpacks-en
  - glibc-langpack-en

__sap_general_preconfigure_packages: "{{ lookup('vars', '__sap_general_preconfigure_packages_' + ansible_facts['architecture']) }}"
