# SPDX-License-Identifier: Apache-2.0
---
- name: Ensure required defaults are read from setup module
  when: >
    not ((ansible_facts['hostname'] is defined) and
    (ansible_facts['domain'] is defined) and
    (ansible_facts['default_ipv4'] is defined))
  ## this is equivalent to
  # (ansible_facts['hostname'] is undefined) or
  # (ansible_facts['domain'] is undefined) or
  # (ansible_facts['default_ipv4'] is defined)
  ansible.builtin.setup:
    gather_subset: "{{ __sap_maintain_etc_hosts_gather_subset }}"
    filter:
      - "ansible_facts['hostname']"
      - "ansible_facts['domain']"
      - "ansible_facts['default_ipv4']"

- name: Ensure sap_maintain_etc_hosts_list is correctly defined
  when: sap_maintain_etc_hosts_list is defined and sap_maintain_etc_hosts_list | length > 0
  block:
    - name: Get list of hosts to be added with no state definition
      ansible.builtin.set_fact:
        __sap_maintain_etc_hosts_fact_present: "{{ sap_maintain_etc_hosts_list | selectattr('state', 'undefined') | list }}"

    - name: Add list of hosts with state=present
      ansible.builtin.set_fact:
        __sap_maintain_etc_hosts_fact_present: "{{ __sap_maintain_etc_hosts_fact_present +
          (sap_maintain_etc_hosts_list | difference(__sap_maintain_etc_hosts_fact_present) | selectattr('state', 'eq', 'present') | list) }}"

    - name: Debug list of hosts to be present
      ansible.builtin.debug:
        msg:
          - "{{ __sap_maintain_etc_hosts_fact_present }}"
        verbosity: 2

    - name: Ensure no duplicate IPs are in the list for adding to hosts
      ansible.builtin.assert:
        that:
          (__sap_maintain_etc_hosts_fact_present | map(attribute='node_ip') | length) ==
          (__sap_maintain_etc_hosts_fact_present | map(attribute='node_ip') | unique | length)
        fail_msg: "FAIL: You have defined duplicate ip addresses to be created!"

    - name: Ensure no duplicate hostnames are in the list for adding to hosts
      ansible.builtin.assert:
        that:
          (__sap_maintain_etc_hosts_fact_present | map(attribute='node_name') | length) ==
          (__sap_maintain_etc_hosts_fact_present | map(attribute='node_name') | unique | length)
        fail_msg: "FAIL: You have defined duplicate hostnames to be created!"

    - name: Set hosts list variable from sap_maintain_etc_hosts_list
      ansible.builtin.set_fact:
        __sap_maintain_etc_hosts_fact_hosts_list: "{{ sap_maintain_etc_hosts_list }}"

# set defaults for local host if sap_maintain_etc_hosts_list is empty
- name: Set hosts list variable to defaults
  when: >
    ( sap_maintain_etc_hosts_list is undefined) or
    ( sap_maintain_etc_hosts_list is none) or
    ( sap_maintain_etc_hosts_list | trim == '') or
    ( sap_maintain_etc_hosts_list | length == 0)
  ansible.builtin.set_fact:
    __sap_maintain_etc_hosts_fact_hosts_list:
      - node_ip: "{{ ansible_facts['default_ipv4'].address }}"
        node_name: "{{ ansible_facts['hostname'] }}"
        node_domain: "{{ sap_domain | default(ansible_facts['domain']) }}"
        node_comment: "managed by Ansible role sap_maintain_etc_hosts"
        state: present

- name: Get the content of /etc/hosts
  ansible.builtin.slurp:
    src: "{{ __sap_maintain_etc_hosts_file }}"
  register: __sap_maintain_etc_hosts_register_file

- name: Add entry to "{{ __sap_maintain_etc_hosts_file }}"
  loop: "{{ __sap_maintain_etc_hosts_fact_hosts_list }}"
  loop_control:
    label: "{{ thishost.node_name | d(thishost.node_ip) }}"
    loop_var: thishost
  ansible.builtin.include_tasks:
    file: update_host_{{ thishost.state | default('present') }}.yml
