# SPDX-License-Identifier: Apache-2.0
---
- name: Hosts File - Absence - Verify that variable node_ip is in the correct format
  ansible.builtin.assert:
    that:
      - (__etc_hosts_item.node_ip | regex_search(sap_maintain_etc_hosts_regexp_ipv4) is not none
          and __etc_hosts_item.node_ip | regex_search(sap_maintain_etc_hosts_regexp_ipv4) | length > 0)
        or (__etc_hosts_item.node_ip | regex_search(sap_maintain_etc_hosts_regexp_ipv6) is not none
          and __etc_hosts_item.node_ip | regex_search(sap_maintain_etc_hosts_regexp_ipv6) | length > 0)
    fail_msg: |
      FAIL: The IP address of this host does not have a correct format!
        Configure the IP address appropriately in of the following variables:
        - sap_ip
        - sap_maintain_etc_hosts_list, member node_ip
  when: thisnode.node_ip is defined

- name: Hosts File - Absence - Ensure that either IP address or hostname is defined
  ansible.builtin.assert:
    that: >
      ((__etc_hosts_item.node_ip is defined) and (__etc_hosts_item.node_name is undefined) and (__etc_hosts_item.node_domain is undefined)) or
      ((__etc_hosts_item.node_ip is undefined) and (__etc_hosts_item.node_name is defined))
    fail_msg: |
      FAIL: Invalid delete item!
        Define either node_ip only or node_name. In the latter case, node_domain is optional.

- name: Hosts File - Absence - Ensure that all entries with IP {{ __etc_hosts_item.node_ip | d('undefined') }} in /etc/hosts are absent
  ansible.builtin.lineinfile:
    path: "{{ __sap_maintain_etc_hosts_file }}"
    regexp: '^{{ __etc_hosts_item.node_ip }}\s'
    state: absent
    backup: true
  when:
    - __etc_hosts_item.node_ip is defined
    - __etc_hosts_item.node_name is undefined
    - not ansible_check_mode
  become_user: root
  become: true

- name: Hosts File - Absence - Ensure that all entries with name {{ __etc_hosts_item.node_name | d('undefined') }} in /etc/hosts are absent
  ansible.builtin.lineinfile:
    path: "{{ __sap_maintain_etc_hosts_file }}"
    regexp: '^.*\s{{ __etc_hosts_item.node_name }}\s'
    state: absent
    backup: true
  when:
    - __etc_hosts_item.node_name is defined
    - (__etc_hosts_item.node_domain is undefined) or (__etc_hosts_item.node_domain | length == 0)
    - __etc_hosts_item.node_ip is undefined
    - not ansible_check_mode
  become_user: root
  become: true

- name: Hosts File - Absence - Ensure that all enries with the specified FQDN in /etc/hosts are absent
  ansible.builtin.lineinfile:
    path: "{{ __sap_maintain_etc_hosts_file }}"
    regexp: '^.*\s{{ __etc_hosts_item.node_name + "." + __etc_hosts_item.node_domain }}\s'
    state: absent
    backup: true
  when:
    - __etc_hosts_item.node_name is defined
    - __etc_hosts_item.node_domain is defined
    - __etc_hosts_item.node_domain | length > 0
    - __etc_hosts_item.node_ip is undefined
    - not ansible_check_mode
  become_user: root
  become: true
