# SPDX-License-Identifier: Apache-2.0
---
- name: Hosts File - Presence - Verify that 'node_ip' is set
  ansible.builtin.assert:
    that:
      - __etc_hosts_item.node_ip is defined
      - __etc_hosts_item.node_ip is not none
      - __etc_hosts_item.node_ip | trim != ''
    fail_msg: |
      FAIL: The IP address of this host not known!
        Configure your managed node accordingly or set one of the following variables:
        - sap_ip
        - sap_maintain_etc_hosts_list, member node_ip

- name: Hosts File - Presence - Verify that 'node_ip' is using the correct IP address format
  ansible.builtin.assert:
    that:
      - (__etc_hosts_item.node_ip | regex_search(sap_maintain_etc_hosts_regexp_ipv4) is not none
          and __etc_hosts_item.node_ip | regex_search(sap_maintain_etc_hosts_regexp_ipv4) | length > 0)
        or (__etc_hosts_item.node_ip | regex_search(sap_maintain_etc_hosts_regexp_ipv6) is not none
          and __etc_hosts_item.node_ip | regex_search(sap_maintain_etc_hosts_regexp_ipv6) | length > 0)
    fail_msg: |
      FAIL: The IP address of this host does not have a correct format!
        Configure the IP address appropriately in of the following variables:
        - sap_ip
        - sap_maintain_etc_hosts_list, member node_ip

- name: Hosts File - Presence - Verify that 'node_name' is set
  ansible.builtin.assert:
    that: not(
      (__etc_hosts_item.node_name is undefined) or
      (__etc_hosts_item.node_name is none) or
      (__etc_hosts_item.node_name | trim == ''))
    fail_msg: |
      FAIL: The hostname of this host is not known!
        Configure your managed node accordingly or set one of the following variables:
        - sap_hostname
        - sap_maintain_etc_hosts_list, member node_name

- name: Hosts File - Presence - Set the variable for the DNS domain
  ansible.builtin.set_fact:
    __sap_maintain_etc_hosts_fact_domain:
      "{{ __etc_hosts_item.node_domain if __etc_hosts_item.node_domain is defined and __etc_hosts_item.node_domain != ''
        else (sap_domain if sap_domain is defined and sap_domain != '' else ansible_facts['domain'] | d('')) }}"

- name: Hosts File - Presence - Verify that the DNS domain is set
  ansible.builtin.assert:
    that: >
      not( ( __sap_maintain_etc_hosts_fact_domain is undefined) or
      ( __sap_maintain_etc_hosts_fact_domain is none) or
      ( __sap_maintain_etc_hosts_fact_domain | trim == '') )
    fail_msg: |
      FAIL: The DNS domain of this host not known!
        Configure your DNS accordingly or set one of the following variables:
        - sap_domain
        - sap_maintain_etc_hosts_list, member node_domain

- name: Hosts File - Presence - Set default values for comment and alias mode
  ansible.builtin.set_fact:
    __sap_maintain_etc_hosts_fact_comment: >-
      {{
        (('# ' + __etc_hosts_item.node_comment) if __etc_hosts_item.node_comment is defined else '') +
        ((' ' + __etc_hosts_item.hana_site) if __etc_hosts_item.hana_site is defined else '') | trim
      }}
    __sap_maintain_etc_hosts_fact_alias_mode: "{{ __etc_hosts_item.alias_mode | default('merge') }}"

- name: Hosts File - Presence - Merge existing aliases with new alias list
  when: __sap_maintain_etc_hosts_fact_alias_mode != "overwrite"
  block:
    - name: Hosts File - Presence - Extract existing aliases from /etc/hosts for {{ __etc_hosts_item.node_ip }}
      ansible.builtin.set_fact:
        __sap_maintain_etc_hosts_fact_existing_aliases:
          "{{ (__sap_maintain_etc_hosts_register_file['content'] | b64decode).split('\n')
            | select('match', '^' ~ __etc_hosts_item.node_ip ~ '\\s')
            | map('regex_replace', '#.*$', '')
            | map('split') | flatten
            | reject('equalto', __etc_hosts_item.node_ip)
            | reject('equalto', __etc_hosts_item.node_name)
            | reject('equalto', __etc_hosts_item.node_name ~ '.' ~ __sap_maintain_etc_hosts_fact_domain) }}"

    - name: Hosts File - Presence - Add defined aliases
      ansible.builtin.set_fact:
        __sap_maintain_etc_hosts_fact_aliases:
          "{{ (__sap_maintain_etc_hosts_fact_existing_aliases + __etc_hosts_item.aliases
              if ('aliases' in __etc_hosts_item and __etc_hosts_item.aliases is not none) else [])
              | unique | join(sap_maintain_etc_hosts_delimiter) | trim }}"

- name: Hosts File - Presence - Overwrite existing aliases
  when: __sap_maintain_etc_hosts_fact_alias_mode == "overwrite"
  ansible.builtin.set_fact:
    __sap_maintain_etc_hosts_fact_aliases: "{{ __etc_hosts_item.aliases | d([]) | unique | join(sap_maintain_etc_hosts_delimiter) }}"

- name: Hosts File - Presence - Display host, DNS domainname and IP address before the modification
  ansible.builtin.debug:
    msg:
      - "hostname   = '{{ __etc_hosts_item.node_name }}'"
      - "domain     = '{{ __sap_maintain_etc_hosts_fact_domain }}'"
      - "ip         = '{{ __etc_hosts_item.node_ip }}'"
      - "comment    = '{{ __sap_maintain_etc_hosts_fact_comment }}'"
      - "aliases    = '{{ __sap_maintain_etc_hosts_fact_aliases }}'"
      - "alias mode = '{{ __sap_maintain_etc_hosts_fact_alias_mode }}'"

# We allow more than one line containing sap_ip:
- name: Hosts File - Presence - Count entries for {{ __etc_hosts_item.node_ip }}
  ansible.builtin.set_fact:
    __sap_maintain_etc_hosts_fact_ip_count:
      "{{ (__sap_maintain_etc_hosts_register_file['content'] | b64decode).split('\n')
        | select('match', '^' ~ (__etc_hosts_item.node_ip | regex_escape) ~ '\\s')
        | list | length }}"
  when: not ansible_check_mode

- name: Hosts File - Presence - Report if there is more than one line with the IP address
  ansible.builtin.debug:
    msg:
      - "INFO: More than one line containing '{{ __etc_hosts_item.node_ip }}'. File {{ __sap_maintain_etc_hosts_file }} will not be modified."
  when:
    - not ansible_check_mode
    - __sap_maintain_etc_hosts_fact_ip_count | int > 1

- name: Hosts File - Presence - Ensure that node_name is not part of the localhost entry
  ansible.builtin.replace:
    path: "{{ __sap_maintain_etc_hosts_file }}"
    regexp: '^(127.0.0.1 .*)\s{{ line_item }}(\s.*)$'
    replace: '\1\2'
    backup: true
  when:
    - not ansible_check_mode
    - __sap_maintain_etc_hosts_fact_ip_count | int <= 1
  become_user: root
  become: true
  loop:
    - "{{ __etc_hosts_item.node_name }}.{{ __sap_maintain_etc_hosts_fact_domain }}"
    - "{{ __etc_hosts_item.node_name }}"
  loop_control:
    loop_var: line_item

- name: Hosts File - Presence - Ensure that the entry for node_ip in {{ __sap_maintain_etc_hosts_file }} is correct
  ansible.builtin.lineinfile:
    path: "{{ __sap_maintain_etc_hosts_file }}"
    regexp: '^{{ __etc_hosts_item.node_ip }}\s'
    line: >-
      {{ __etc_hosts_item.node_ip }}{{ sap_maintain_etc_hosts_delimiter }}{{
      __etc_hosts_item.node_name }}.{{ __sap_maintain_etc_hosts_fact_domain }}{{ sap_maintain_etc_hosts_delimiter }}{{
      __etc_hosts_item.node_name }}{{
      (sap_maintain_etc_hosts_delimiter + __sap_maintain_etc_hosts_fact_aliases)
        if __sap_maintain_etc_hosts_fact_aliases | length > 0 else '' }}{{
      (sap_maintain_etc_hosts_delimiter + __sap_maintain_etc_hosts_fact_comment)
        if __sap_maintain_etc_hosts_fact_comment | length > 0 else '' }}
    backup: true
  when:
    - not ansible_check_mode
    - __sap_maintain_etc_hosts_fact_ip_count | int <= 1
  become_user: root
  become: true

# After all nodes are added or deleted, run the consistency check against the hosts file

- name: Hosts File - Presence - Get the content of /etc/hosts again after possible modification
  ansible.builtin.slurp:
    src: "{{ __sap_maintain_etc_hosts_file }}"
  register: __sap_maintain_etc_hosts_register_file_post_modification

- name: Hosts File - Presence - Check for duplicate or missing entries of hostname and fqdn in {{ __sap_maintain_etc_hosts_file }}
  ansible.builtin.assert:
    that: (__sap_maintain_etc_hosts_register_file_post_modification['content'] | b64decode).split('\n')
        | reject('match', '^#')
        | select('search', '\\s' ~ __sap_maintain_etc_hosts_line_item ~ '(\\s|$)')
        | length == 1
    fail_msg: "FAIL: Hostname or FQDN '{{ __sap_maintain_etc_hosts_line_item }}' is not exactly once in {{ __sap_maintain_etc_hosts_file }}!"
    success_msg: "PASS: Hostname or FQDN '{{ __sap_maintain_etc_hosts_line_item }}' exists exactly once."
  loop:
    - "{{ __etc_hosts_item.node_name }}.{{ __sap_maintain_etc_hosts_fact_domain }}"
    - "{{ __etc_hosts_item.node_name }}"
  loop_control:
    loop_var: __sap_maintain_etc_hosts_line_item
  when: not ansible_check_mode

- name: Hosts File - Presence - Perform the hosts file completeness check
  ansible.builtin.set_fact:
    __sap_maintain_etc_hosts_fact_completeness_count:
      "{{ (__sap_maintain_etc_hosts_register_file_post_modification['content'] | b64decode).split('\n')
        | reject('match', '^\\s*#')
        | select('search', __etc_hosts_item.node_ip)
        | select('search', __etc_hosts_item.node_name ~ '.' ~ __sap_maintain_etc_hosts_fact_domain)
        | select('search', '\\s' ~ __etc_hosts_item.node_name ~ '(\\s|$)')
        | length }}"

- name: Hosts File - Presence - Verify completeness of hosts file entry
  ansible.builtin.assert:
    that:
      - __sap_maintain_etc_hosts_fact_completeness_count | int == 1
    fail_msg: |
      FAIL: Your server's ip4 address, FQDN, or hostname are not in {{ __sap_maintain_etc_hosts_file }}!
        Expected:
      {{ __etc_hosts_item.node_ip }} {{ __etc_hosts_item.node_name }}.{{ __sap_maintain_etc_hosts_fact_domain }} {{ __etc_hosts_item.node_name }}
    success_msg: "All required entries (IP, FQDN, hostname) found exactly once in {{ __sap_maintain_etc_hosts_file }}."
  ignore_errors: "{{ ansible_check_mode }}"
